Add versioning support to Dockerfile and app footer (#35)
- Update Dockerfile to set APP_VERSION from build environment
- Modify app.py to display the current version in the footer
- Implement a check for tag presence in the build workflow

diff --git a/.github/workflows/build_and_push_image.yaml b/.github/workflows/build_and_push_image.yaml
--- a/.github/workflows/build_and_push_image.yaml
+++ b/.github/workflows/build_and_push_image.yaml
@@ -25,6 +25,13 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Ensure tag present and set APP_VERSION
+        run: |
+          if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
+            echo "No tag found; failing build." && exit 1
+          fi
+          echo "APP_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
       
       - name: Log in to the Container registry
         uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
@@ -55,6 +62,8 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+          build-args: |
+            APP_VERSION=${{ env.APP_VERSION }}
 
       - name: Generate artifact attestation
         uses: actions/attest-build-provenance@v2
